version: "3.9"
services:
  db:
    container_name: sql-test
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /home/arunangsu.sahu@abzooba.taas.com/Downloads/sql_test/sql:/docker-entrypoint-initdb.d
      - /home/arunangsu.sahu@abzooba.taas.com/Downloads/sql_test/data:/var/lib/mysql
      - /home/arunangsu.sahu@abzooba.taas.com/Downloads/sql_test/sql_conf:/etc/mysql/conf.d